### ISSUE TITLE
Event enrichment fails in some situations

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1178]
This issue is based on https://github.com/inspektor-gadget/inspektor-gadget/issues/1001#issuecomment-1335943053. 

Different gadgets use the [DataEnricher](https://github.com/inspektor-gadget/inspektor-gadget/blob/1c2f1abff6f6f4d3b13addf6fb3f6e16bc2ae164/pkg/gadgets/helpers.go#L45-L47) to add container information to the events received from the eBPF programs. Example [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/1c2f1abff6f6f4d3b13addf6fb3f6e16bc2ae164/pkg/gadgets/trace/exec/tracer/tracer.go#L174). This is possible that by the time the tracer calls `.Enrich()` the container is gone and then the container information from the event is missing.

### Reproducer

1. Execute the following script that creates and removes containers:
```bash
#! /bin/bash

while true
do
        docker run --rm --name we-broke-it ubuntu readlink /proc/self/ns/mnt &
        docker run --rm --name no-yet ubuntu cat /dev/null &

        for job in `jobs -p`
        do
        wait $job
        done
done
```

2. Stress one core on the CPU
```
$ taskset 0x4 stress-ng -c 1
```
3. Execute local-gadget bound to a single thread with the lowest priority 
```
$  sudo taskset 0x4 nice -20 ./local-gadget trace exec -c no-yet

...
no-yet                                            191525     191477     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            191785     191751     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            192043     191998     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            192300     192238     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            192557     192512     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            192829     192791     cat              0   /usr/bin/cat /dev/null                                           
                                                  193109     193074     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            193366     193304     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            193622     193570     cat              0   /usr/bin/cat /dev/null                                           
no-yet                                            193878     193848     cat              0   /usr/bin/cat /dev/null                                     
``` 

Some of the events miss the container data. 

### Cause

There is a time of window from the moment the event is captured in the kernel and it's enriched in user space, it's possible that the container is removed in that interval. 

### Possible solution

Implement container cache mechanism, i.e. the enrichment still works a bit after the container is removed, this to give time for the tracers to perform this operation. Of course deciding how long to keep those containers is difficult, I'd say that something like 1 second should be good enough.

**Comment by mauriciovasquezbernal** [comment]
I found a reproducer in kubectl-gadget without having to use taskset nor similar tricks. I was able to reproduce on an AKS cluster and also in a local kubeadm one:

1. Deploy the following manifest. (It's possible that it can be reproduce with a simple one, but I haven't tried)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 2
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "1024"
      containers:
        - name: mycontainer
          image: docker.io/mauriciovasquezbernal/mynginx:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - DAC_READ_SEARCH
              - FOWNER
              - SETUID
              - SETGID
              - SYS_ADMIN
```

```bash
$  kubectl apply -f mydeployment.yaml
```

2. Remove pods in a loop:

```bash
$ while true; do kubectl -n demo delete pod --all; done
```

3. Execute kubectl-gadget and pipe to jq to detect when the namespace is empty:

```bash
$ ./kubectl-gadget trace capabilities -o json -n demo | jq '.namespace' | grep null
# after some seconds it'll print null messages
null
null
null
null
null
null
null
null

...
```

PD: Some times it prints the `err: node aks-agentpool-xxx-yyy Error reading perf ring buffer: bad file descriptor` error message.


I tried with old versions and them are affected too, even if it seems to me it's easier to reproduce with main. 

Tested on 99c6cbea6522bd1b17964506fcbcffa3cb10bad7.
