### ISSUE TITLE
ig: Doesn't support non-root k8s containers with cri-o 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#1692]
`ig` is not able to capture events from non-root k8s containers when using cri-o

```bash 
# build ig (can also use make ig)
$ cd cmd/ig
$ go build . 

# create a minikube cluster with cri-o
$ minikube start --container-runtime cri-o

$ minikube cp ig /ig
$ minikube ssh "sudo chmod +x /ig && sudo /ig trace exec -r cri-o"
CONTAINER                                         PID        PPID       COMM             RET ARGS
```

## working case

Deploy the following pod:

```yaml
# foo.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  securityContext:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: test-pod-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - while true; do cat /dev/null ; sleep 0.1; done
```

```bash
$ kubectl apply -f foo.yaml 
pod/test-pod created
```

Events are captured by ig:

```bash
.... 
test-pod-container                                82476      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82477      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82478      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82479      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82480      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82499      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82506      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82507      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82508      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82509      82037      cat              0   /bin/cat /dev/null                                               
test-pod-container                                82510      82037      cat              0   /bin/cat /dev/nul
...
```

```bash
$ kubectl delete -f foo.yaml
```

### not working case

Deploy this foo: (notice the `runAsUser: 1000`)

```yaml
# foo.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: test-pod-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - while true; do cat /dev/null ; sleep 0.1; done
```

```bash
$ kubectl apply -f foo.yaml 
pod/test-pod created
```

ig shows a warning and no events are captured:

```bash
WARN[0050] error watching pid: stat /run/containers/storage/overlay-containers/a6df164f0a7955c9587383329e871a56883283c4a8dbac48fa95d5012d1d95aa/userdata/pidfile: no such file or directory 
```

```bash
$ kubectl apply -f foo.yaml 
pod/test-pod created
```
