### ISSUE TITLE
[trace exec] [GCP] Container-collection failing to initialize on GKE (Ubuntu / containerd)

### ISSUE THREAD

**Issue by galofir-ms** [inspektor-gadget/inspektor-gadget#2335]
## Description

Container-collection is not being created, leading to unprocessed process events coming from containers

See these error logs:
```bash
root@debug-pod:/# ig trace exec --verbose --auto-mount-filesystems -o columns=k8s
DEBU[0000] bpf already mounted
DEBU[0000] debugfs already mounted
DEBU[0000] tracefs already mounted
WARN[0000] Failed to create container-collection
DEBU[0000] Failed to create container-collection: getting host net ns inode: stat /proc/1/ns/net: permission denied
DEBU[0000] > canEnrichEvent: true
DEBU[0000]      > canEnrichEventFromMountNs: true
DEBU[0000]      > canEnrichEventFromNetNs: false
DEBU[0000] > isMountNsMapSetter: true
DEBU[0000] > isAttacher: false
K8S.NODE                                         K8S.NAMESPACE                                    K8S.POD                                          K8S.CONTAINER
DEBU[0000] running with local runtime
DEBU[0000] found 1 operators:
DEBU[0000]   LocalManager
DEBU[0000] set event handler
DEBU[0000] calling operator.PreGadgetRun()
Error: running gadget: gadget prerun: pre gadget run on operator "LocalManagerTrace": container-collection isn't available
```

## Impact

Data collection is incomplete without container process events

## Environment and steps to reproduce

1. **Set-up**: 
 - GCP project
 - GKE cluster (standard, not auto-pilot), Ubuntu nodes: 
 ```bash
root@debug-pod:/# uname -a
Linux debug-pod 5.15.0-1036-gke #41-Ubuntu SMP Wed Jun 7 04:23:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
 - Install IG latest (v0.23.1) on node from instructions @ https://www.inspektor-gadget.io/docs/latest/getting-started/install-linux/
 - deploy pod to allow us to exec to node. **Pod has all required capabilities documented and hostfs monted to /host** 
 ```yaml
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu:latest
    command: ["sleep", "3600"]
    securityContext:
      seLinuxOptions:
       type: unconfined_t
      capabilities:
        add: ["SYS_ADMIN", "SYS_RESOURCE", "SYS_PTRACE", "SYSLOG", "IPC_LOCK"]
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /
  ```
3. **Task**: collecting container process events via `ig trace exec`
4. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. Create Standard GKE cluster with Ubuntu node images (C-OS not tested)
  b. Deploy pod as described above
  c. Install IG on node
  d. Run ig trace exec
5. **Error**: See error logs above

## Expected behavior

Process events emitted from containers

**Comment by galofir-ms** [comment]
Hello, I tried different capability permutations, even:

```yaml
      capabilities:
        add:
          - SYS_ADMIN
          - SYS_PTRACE
          - IPC_LOCK
          - NET_ADMIN
          - SYSLOG
          - NET_RAW
```

The only thing that worked unfortunately was privileged container. If we have no choice this is what we'll go with.

**Comment by dorser** [comment]
This is likely related to GKE applying AppArmor security policies by default.
I tried the following on K3s with AppArmor enabled and it seems to be working:

```
apiVersion: v1
kind: Pod
metadata:
 name: debug-pod
 annotations:
   container.apparmor.security.beta.kubernetes.io/debug-container: unconfined
...
```
