### ISSUE TITLE
ig "--auto-mount-filesystems" logic invalid on Amazon Linux

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2426]
## Description

On EKS with Linux `5.10.205-195.804.amzn2.x86_64`, running `ig` in a pod errors out with:
```
error: filesystems tracefs not mounted (did you try --auto-mount-filesystems?)
```
Even when `/sys/kernel` is bind mounted from the host.

While using `--auto-mount-filesystems` solves the issue, it is an unnecessarily strict check because `ig` checks for tracefs on `/sys/kernel/tracing` but on Amazon Linux, it is not mounted there. It is only mounted **on-demand** on `/sys/kernel/debug/tracing` (notice the **debug** directory).

## Impact

* Confusing check and error message
* `--auto-mount-filesystems` is a workaround but not the correct solution

## Environment and steps to reproduce

* `kubectl apply` this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ig
  labels:
    k8s-app: example-ig
spec:
  containers:
    - name: ig
      image: ghcr.io/inspektor-gadget/ig:latest
      securityContext:
        privileged: true
      command:
        - "ig"
        - "trace"
        - "exec"
        - "--host"
      env:
        - name: HOST_ROOT
          value: "/host"
      volumeMounts:
        - mountPath: /host
          name: host
        - mountPath: /run
          name: run
        - mountPath: /sys/kernel
          name: debugfs
  nodeName: CHANGEME.compute.internal
  volumes:
    - name: host
      hostPath:
        path: /
    - name: run
      hostPath:
        path: /run
    - name: debugfs
      hostPath:
        path: /sys/kernel
```

* Check logs with `kubectl logs ig`
* Notice the error

```
error: filesystems tracefs not mounted (did you try --auto-mount-filesystems?)
```

## Expected behavior

* ig should check both `/sys/kernel/tracing` and `/sys/kernel/debug/tracing`

According to my tests, `unix.Statfs()` on the tracing directory is enough to trigger the automount.

## Additional information

Using kubetl-debug-node and chroot to access the host:

```
$ kubectl debug node/$NODE -ti --image=ubuntu -- chroot /host /bin/bash
# uname -r
5.10.205-195.804.amzn2.x86_64
# cat /proc/self/mountinfo |grep ' /sys/kernel'
2227 2226 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime - securityfs securityfs rw
2241 2226 0:7 / /sys/kernel/debug rw,relatime - debugfs debugfs rw
# ls -l /sys/kernel/tracing
total 0
# ls -l /sys/kernel/debug/tracing | wc -l
52
# cat /proc/self/mountinfo |grep ' /sys/kernel'
2227 2226 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime - securityfs securityfs rw
2241 2226 0:7 / /sys/kernel/debug rw,relatime - debugfs debugfs rw
1741 2241 0:10 / /sys/kernel/debug/tracing rw,relatime - tracefs tracefs rw
# exit
exit
```

Notice that:
* Initially, **tracefs is not mounted anywhere**
* It gets **automatically mounted** when accessing `/sys/kernel/debug/tracing` but **only at that location**
* When exiting the kubetl-debug-node and chroot session and restarting again, **tracefs is unmounted again**
