### ISSUE TITLE
The seccomp policy created by the advisor is not enough to start the pod when using allowPrivEsc=true

### ISSUE THREAD

**Issue by margamanterola** [inspektor-gadget/inspektor-gadget#267]
## Description

I tried using the seccomp policy advisor to create the policy for a pod in an Azure VM running Ubuntu Hirsute, using Minikube with the driver=none option. 

I managed to get the seccomp policy advisor to run and generate a policy both in the "Status" mode and in the "ExternalResource" mode, using the security profiles operator.

I then edited the workload and added the seccomp policy served by the operator and restarted the pod. Which caused the pod to fail with: `Error: failed to start container "hello-python": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: close exec fds: ensure /proc/self/fd is on procfs: operation not permitted: unknown`

Changing the default policy to LOG instead of ERRNO, I see a bunch of SECCOMP errors in journalctl, for different syscalls (snippet):
```
Sep 11 09:58:02 hirsute-demo audit[566404]: SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 subj=unconfined pid=566404 comm="runc:[2:INIT]" exe="/" sig=0 arch=c000003e syscall=125 compat=0 ip=0x4c1b3b code=0x7ffc0000
Sep 11 09:58:02 hirsute-demo audit[566404]: SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 subj=unconfined pid=566404 comm="runc:[2:INIT]" exe="/" sig=0 arch=c000003e syscall=126 compat=0 ip=0x4c1b3b code=0x7ffc0000
Sep 11 09:58:02 hirsute-demo audit[566404]: SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 subj=unconfined pid=566404 comm="runc:[2:INIT]" exe="/" sig=0 arch=c000003e syscall=262 compat=0 ip=0x4c1baa code=0x7ffc0000
```

The syscalls logged and their meanings on 64bit:
* 80 chdir
* 93 fchown
* 125 capget
* 126 capset
* 262 newfstatat

I tried deleting and starting the pod a few times and capturing that with the trace, but the policies generated were always the same. In other words, it consistently generates a policy that's missing some critical syscalls needed to start the pod.

I suspect this is related to the fact that I'm using the driver=none option which means that this is running directly on the VM without another layer in between. However, I can't know for sure as I don't have any instance where this is working correctly.

## Impact

The policies generated by the advisor are not enough to get the pod to run successfully.

## Environment and steps to reproduce

1. **Set-up**: 
  * Azure VM running Ubuntu Hirsute
  * Latest Minikube version, using `--driver=none`
  * Latest IG, compiled and deployed from source
  * The following files:
  
`seccomp-operator.sh` (installs the operator in the cluster):
```
#!/bin/bash
set -x
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.1/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/master/deploy/operator.yaml
```

`uwsgi.yaml` (demo workload):
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: seccomp-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-script
  namespace: seccomp-demo
data:
  main.py: |
    from flask import Flask
    app = Flask(__name__)
    @app.route("/")
    def hello():
        return "Hello World!\n"
    if __name__ == "__main__":
        app.run(host="0.0.0.0", debug=True, port=80)
  uwsgi.ini: |
    [uwsgi]
    module=main
    callable=app
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: seccomp-demo
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-python
  namespace: seccomp-demo
  labels:
    app: hello-python
spec:
  securityContext:
    #seccompProfile:
      #type: Localhost
      #localhostProfile: operator/gadget/myseccomp.json
  containers:
  - name: hello-python
    image: tiangolo/uwsgi-nginx-flask:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: app-script
      mountPath: /app/
  volumes:
  - name: app-script
    configMap:
      name: app-script
      items:
        - key: main.py
          path: main.py
        - key: uwsgi.ini
          path: uwsgi.ini
```

`trace-seccomp.yaml` (tracing CRD):
```
apiVersion: gadget.kinvolk.io/v1alpha1
kind: Trace
metadata:
  name: seccomp
  namespace: gadget
spec:
  node: hirsute-demo
  gadget: seccomp
  filter:
    namespace: seccomp-demo
    podname: hello-python
  runMode: Manual
  outputMode: ExternalResource
  output: gadget/myseccomp
```

2. **Task**: Generate the policies for the workload and store them with the operator
3. **Actions**: 
  a. Apply the CRD: `kubectl apply -f trace-seccomp.yaml`
  b. Annotate it to start: `kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=start`
  c. Apply the workload: `kubectl apply -f uwsgi.yaml`
  d. Get the service IP/Port and Curl it: `curl $(minikube service hello-python-service -n seccomp-demo --url=true)`
  e. Generate the policies: `kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=generate`
  f. Verify that the profile was created: `kubectl get -n gadget seccompprofile`
  g. Modify `uwsgi.yaml`, remove the `#` in the lines commented, then reload the workload by deleting and re-applying the file.
4. **Error**:  The pod fails to start with:
```
  Warning  Failed     7s (x3 over 23s)  kubelet            Error: failed to start container "hello-python": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: close exec fds: ensure /proc/self/fd is on procfs: operation not permitted: unknown
```

## Expected behavior

The pod should start successfully with the generated policies

## Additional information

I tried this several times and the policies generated were consistent.  When I modified the policy to make it log instead of block, the pod came up successfully. I traced that one and the policy generated was still the same.
