### ISSUE TITLE
[RFE] Implement event generation

### ISSUE THREAD

**Issue by mqasimsarfraz** [inspektor-gadget/inspektor-gadget#3560]
The issue describes the user experience and implementation details for event generation:

## User experience (UX)

The event generation will be tied to a single gadget run and controlled using operator's parameters i.e., CLI flags or paramValues in https://github.com/inspektor-gadget/inspektor-gadget/pull/3515. Following are the examples:

### flags

 ```bash
$ ig run trace_dns --filter name==example.com. --eventgen-enable=true --eventgen-type=dns --eventgen-target=example.com
```
or
```
$ kubectl gadget run --filter name==example.com. --eventgen-enable=true --eventgen-type=dns --eventgen-target=example.com
```

or using instance manifest via:

```yaml
version: 1
kind: instance-spec
image: trace_dns
name: capture_dns_events
paramValues:
    operator.filter.filter: "name==example.com."
    operator.eventgen.eventgen-enable: true
    operator.eventgen.eventgen-type: dns
    operator.eventgen.eventgen-target: example.com
```
### Implementation details:

In terms of implementation it will be implemented as an [operator](https://www.inspektor-gadget.io/docs/latest/spec/operators/) and:
- The generation of events must happen on server side except for Kubernetes (see below).
- The environment where events will be generated shouldn't be tight to Kubernetes (probably what you did was just an example). I suggest re-using the [Container interface](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-utils/testutils/container_interface.go#L39) we created for testing. With few changes, it'll allow us to run commands on docker/containerd containers (even though in this case we don't care about the runtime), but also in Kubernetes containers by keeping a common interface. In addition, we can extend it to allow creating container with specific linux namespaces. For instance, to create container with the host network linux namespace for generating DNS or HTTPS events for ig running as standalone with the --host flag.

#### Params:
Currently I think following params should be there:
- [Global] eventgen-enable - To allow admins to disable/enable event generation.
- [Instance] eventgen-type - If specified should start event generation based on the type specified e.g DNS,HTTP,etc.
- [Instance] eventgen-target - Domain name, file name, etc
- [Instance] eventgen-count - Number of events to generate, default "-1" to keep generating events in loop. 
- [Instance] eventgen-extraparams - Extra params to control different event generators e.g DNS record type, Number of retries, etc (maybe this could be part of target?)
