### ISSUE TITLE
oci: it's not possible to define oci operator params on the image spec file

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3676]
The `operator.oci.*` params on an image spec file are ignored.

Apply this diff:

```diff
$ git diff
diff --git a/pkg/operators/oci-handler/oci.go b/pkg/operators/oci-handler/oci.go
index 951a86c4b..eb615fa8b 100644
--- a/pkg/operators/oci-handler/oci.go
+++ b/pkg/operators/oci-handler/oci.go
@@ -247,6 +247,8 @@ func (o *OciHandlerInstance) init(gadgetCtx operators.GadgetContext) error {
                        return fmt.Errorf("getting local oci store: %w", err)
                }

+               fmt.Printf("pull param is %s\n", o.ociParams.Get(pullParam).AsString())
+
                // Make sure the image is available, either through pulling or by just accessing a local copy
                // TODO: add security constraints (e.g. don't allow pulling - add GlobalParams for that)
                err = oci.EnsureImage(gadgetCtx.Context(), gadgetCtx.ImageName(),
@@ -284,6 +286,9 @@ func (o *OciHandlerInstance) init(gadgetCtx operators.GadgetContext) error {
                return fmt.Errorf("unmarshalling metadata: %w", err)
        }

+       annParam := o.ociParams.Get(annotate)
+       fmt.Printf("annotate is %s\n", annParam.AsString())
+
        for _, ann := range o.ociParams.Get(annotate).AsStringSlice() {
                if len(ann) == 0 {
                        continue
```

Running without a manifest works fine

```bash
$ sudo ig run trace_open:latest  --annotate foo:bar --pull always
pull param is always
annotate is foo:bar
```

Params on the manifest are ignored:

```yaml
# manifest.yaml
apiVersion: 1
kind: instance-spec
image: trace_exec
#name: yoyo
tags:
  - foo
  - bar
paramValues:
  operator.oci.annotate: bar:foo
  operator.oci.pull: never
nodes:
  - minikube-m03
```

```bash
$ sudo ig run -f manifest.yaml
pull param is missing
annotate is
```

**Comment by mauriciovasquezbernal** [comment]
I think it's not fixed, consider a similar diff as above:

```diff
$ git diff
diff --git a/pkg/operators/oci-handler/oci.go b/pkg/operators/oci-handler/oci.go
index 8ec82570e..4f83ea2df 100644
--- a/pkg/operators/oci-handler/oci.go
+++ b/pkg/operators/oci-handler/oci.go
@@ -344,6 +344,8 @@ func (o *OciHandlerInstance) init(gadgetCtx operators.GadgetContext) error {

        gadgetCtx.Logger().Debugf("image options: %+v", imgOpts)

+       fmt.Printf("pull param is %q\n", o.ociParams.Get(pullParam).AsString())
+
        target := gadgetCtx.OrasTarget()
        // If the target wasn't explicitly set, use the local store. In this case we
        // need to be sure the image is available.
@@ -386,6 +388,9 @@ func (o *OciHandlerInstance) init(gadgetCtx operators.GadgetContext) error {
                return fmt.Errorf("unmarshalling metadata: %w", err)
        }

+       annParam := o.ociParams.Get(annotate)
+       fmt.Printf("annotate is %q\n", annParam.AsString())
+
        for _, ann := range o.ociParams.Get(annotate).AsStringSlice() {
                if len(ann) == 0 {
                        continue
```

and the same manifest file

```yaml
# manifest.yaml
apiVersion: 1
kind: instance-spec
image: trace_exec:main
#name: yoyo
tags:
  - foo
  - bar
paramValues:
  operator.oci.annotate: bar:foo
  operator.oci.pull: never
nodes:
  - minikube-m03
```

```bash
$ sudo ig run -f manifest.yaml
pull param is "missing"
annotate is ""
RUNTIME.CONTAINERNAME                             COMM                    PID        TID ARGS                         ERR
```
