### ISSUE TITLE
[RFE] Add templates for ustack fields

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#4283]
## Current situation

Gadgets using user stack traces have this kind of fields:
```yaml
      ustack:
        annotations:
          columns.hidden: true
      ustack.addresses:
        annotations:
          description: User stack's addresses
          columns.hidden: true
          columns.width: 20
      ustack.symbols:
        annotations:
          description: User stack's symbols
          columns.hidden: true
          columns.width: 20
```
## Impact

The same field definitions and their annotations are repeated in several gadgets:
- audit_seccomp
- trace_capabilities
- trace_malloc
- trace_open

If we want to change the formatting, we have to change all gadgets using ustack.

## Ideal future situation

Use templates instead of repeating all the annotations.

## Implementation options

- Define a template for ustack.
- Use it in the gadgets above
