### ISSUE TITLE
[RFE] pkg/operators/sort: Allow gadget to set its own default value for `sort` flag

### ISSUE THREAD

**Issue by blanquicet** [inspektor-gadget/inspektor-gadget#4570]
## Current situation

Any gadgets supporting `--sort` flag (e.g., `top_tcp`, `top_file`, `top_process`, etc.) do not sort by default the output.

## Impact

In 99% of cases, users would like to get the output of these gadget already sorted by the counters they provides. For instance, for the `top_tcp` gadget, by `sent_raw` and `received_raw`.

Notice it was already like that for built-in gadgets:

```bash
$ kubectl gadget top tcp --help | grep sort
      --sort string               Sort by columns. Join multiple columns with ','. Prefix a column with '-' to sort in descending order. (default "-sent,-recv")
```

Additionally, users developing their own gadget maybe also will have one counter and they want the output sorted by default.

## Ideal future situation

Gadget developers can configure the default way to sort for their gadgets.

## Implementation options

Like [we did for the `output-mode` in the CLI](https://inspektor-gadget.io/docs/v0.41.0/spec/operators/cli#clidefault-output-mode). The sort operator should provide an annotation to set the default value for sorting a given datasource:

```yaml
name: top tcp
description: Periodically report tcp send receive activity by connection
homepageURL: https://inspektor-gadget.io/
documentationURL: https://www.inspektor-gadget.io/docs/latest/gadgets/top_tcp
sourceURL: https://github.com/inspektor-gadget/inspektor-gadget/tree/main/gadgets/top_tcp
datasources:
  tcp:
    annotations:
      cli.clear-screen-before: "true"
      sort.default-sort: "-sent_raw,-received_raw"
    fields:
      received_raw:
        annotations:
          description: Received bytes
      sent_raw:
        annotations:
          description: Sent bytes
[...]
```
