### ISSUE TITLE
gadgets: Default value for ebpf params is ignored

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#4576]
If I declare an eBPF parameter as:

```c
// program.bpf.c
...
const volatile bool myparam = true;
GADGET_PARAM(myparam);
...
```
and add this to the metadata as:

```yaml
# gadget.yaml
...
params:
  ebpf:
    myparam:
      key: myparam
      defaultValue: "false"
      description: 'TODO: Fill parameter description'
```

the default value on the yaml file is ignored:

```bash
$ sudo ig run hello-world --verify-image=false -h | grep myparam
      --myparam                                TODO: Fill parameter description (default true)
```

This is very confusing, we rather remove the default value from the metadata or ensure it's consistent.
