### ISSUE TITLE
cli: multiple gadget instance specs found in manifest

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#4610]
It's not possible to run a gadget instance manifest with multiple gadgets without using `--detach`

```yaml
#manifest.yaml
apiVersion: 1
kind: instance-spec
image: trace_exec
name: my-gadget-1
paramValues:
  operator.LocalManager.host: true
tags:
  - mytag1
  - mytag2
---
apiVersion: 1
kind: instance-spec
image: trace_open
name: my-gadget-2
```

```bash 
$ sudo ig run -f manifest.yaml
Error: multiple gadget instance specs found in manifest manifest.yaml
```

This limitation makes sense as we don't have a way to show multiple columns at the same time (otherwise the output would be very nasty), however, it should be possible to use this way when using `-o json/yaml`, or just allow it even if the output is nasty with columns.

## Use Case

We want to run a single `ig` binary with multiple gadgets printing events to the screen, then another process will parse those events. 

I explored some alternatives but they don't see to fully satisfy the requirements:

### ig daemon + gadgetctl

Requires also to have the gadgetctl binary available on the system and the caller binary has to call `gadgetctl attach` multiple times. 

### multiple ig instances 

The resource usage is higher (as there is memory duplicated among those ig processes) and the caller process will have to monitor those multiple instances

/cc @johananl
