### ISSUE TITLE
[RFE] Introduce a regression test to ensure we respect liveness probes checks.

### ISSUE THREAD

**Issue by mqasimsarfraz** [inspektor-gadget/inspektor-gadget#950]
## Current situation

Currently nodes with a high number of pods can result in liveness probe check failure e.g #940 resulting in timing out of `kubectl deploy`

## Ideal future situation

We should have a basic regression testing at each change to see if default liveness proble is respected with `110` pods. `110` being default kubelet maximum pods. 

## Implementation options

1. Create a minikube cluster.
2. Deploy a nginx deployment with 110 replicas.
3. Deploy gadget.
4. Make sure the deployment from [3] doesn't timeout.

**Comment by kranurag7** [comment]
Hey @mqasimsarfraz 
I tried to test this on a standard GKE cluster and here's the observation. If I'm targeting a node and creating a nginx deployment with 110 replicas, then this is what I'm seeing in the events. Some of the pods are not starting because of resource constraints. 

<details>
  <summary>Nginx Deployment manifest</summary>
Nginx deployment manifest 

```yaml
$ cat nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: nginx-deployment
spec:
  replicas: 110
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      nodeName: gke-gke-cluster-default-pool-89f526a9-4k5q
$ kubectl create -f nginx.yaml

```
</details>

```bash
$ kubectl get ev 
# truncated
2m1s        Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zp2l9        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
25s         Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zp6q7        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
5m29s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zp8dj        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
2m32s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zpmlq        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
5m33s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zq6x6        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
2m15s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zrbjm        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
2m41s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zsdnh        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
6m7s        Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zsm72        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
2m17s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zssgq        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
2m39s       Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zt52l        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
97s         Warning   OutOfpods                                pod/nginx-deploymentg9h97-5bd76f9bf8-zt825        Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
```
Wanted to ask this before I continue any further on this. 
1. Will the machines that we are using in CI will be able to support 110 pods on a single node? 
2. I've only verified that the gadget daemonset on the respective node, and the gadget pod is not breaking. Does this issue require something else to test?
